### ISSUE TITLE
[BUG] Einstein summation uses 50x more memory without optimize argument specified

### ISSUE THREAD

**Issue by RAMitchell** [nv-legate/cunumeric#1070]
The memory usage without optimize specified seems far out of proportion to the size of the inputs.

legate --mem-usage einsum.py

```Python
import cunumeric as cn

n = 10000
m = 100
X = cn.random.random((n, m))
w = cn.random.random(n)
print("Input memory usage: {} MB".format((X.nbytes + w.nbytes) / 1e6))
cn.einsum('ki,k,kj,k->ij', X, w, X, w)
#cn.einsum('ki,k,kj,k->ij', X, w, X, w, optimize="greedy")
```

**Comment by manopapad** [comment]
This is most likely happening because the trivial pairwise contraction order ends up instantiating a `kji` intermediate array.

```
([(0, 1), (0, -1), (0, -1)],   Complete contraction:  ki,k,kj,k->ij
         Naive scaling:  3
     Optimized scaling:  3
      Naive FLOP count:  4.000e+8
  Optimized FLOP count:  3.010e+8
   Theoretical speedup:  1.329e+0
  Largest intermediate:  1.000e+8 elements
--------------------------------------------------------------------------------
scaling        BLAS                current                             remaining
--------------------------------------------------------------------------------
   2              0               k,ki->ki                           kj,k,ki->ij
   3              0             kj,ki->kji                             k,kji->ij
   3           GEMM              k,kji->ij                                ij->ij)
```

NumPy's `einsum` engine can contract multiple arrays at one time, and that's what happens when `optimize` is `False`, in which case intermediate memory usage is minimal. cuNumeric on the other hand can only contract two arrays at a time, so having a reasonable contraction order is (obviously in hindsight) quite critical.

Fixed in https://github.com/nv-legate/cunumeric/pull/1072, by setting greedy optimization as the default.
