### ISSUE TITLE
Why is cunumeric slower than numpy on the CPU?

### ISSUE THREAD

**Issue by AngryBear2** [nv-legate/cunumeric#1080]
We used step 11 of CFDPython as a test to measure the time spent using cunumeric or numpy. When cunumeric uses cpu, it is also much slower than numpy，In the following figure, the default size is 41.
![image](https://github.com/nv-legate/cunumeric/assets/82449330/452dc02a-5625-4f24-a681-0596ed895faa)
When the GPU is used, the GPU usage is higher than that of the NumPy only when the CFD demo size is expanded to 1111. However, one GPU takes faster time than two GPUs. Is the cfd size too small that causes the GPU to not fully perform?
![image](https://github.com/nv-legate/cunumeric/assets/82449330/593fc640-3590-40ab-b9ce-76b1b7697ca4)
![image](https://github.com/nv-legate/cunumeric/assets/82449330/d6a2ebf3-b2f7-4666-8af4-36b9b31e2822)
Or, is there any CFD demo that better reflects the performance advantage of cunumeric?

**Comment by shriram-jagan** [comment]
please refer to our best practices ([link](https://nv-legate.github.io/cunumeric/23.11/user/practices.html)) on how best to perform benchmarks.

> one GPU takes faster time than two GPUs. Is the cfd size too small that causes the GPU to not fully perform?

Yes. Ideally, you would want to have a large problem size that makes the runtime overheads appear relatively small and also fits in the GPU global memory. But, before that, I would suggest looking at the knobs available in legate, for e.g., by doing `legate --help` and getting familiar with it - it'll be very handy when you try out some of the suggestions given below. I'd recommend finding the available memory capacity on the GPU and pass in about 90 or 95% of that to the `--fbmem` argument in `legate` (for e.g. `legate --fbmem 45000 ...`), and correspondingly increase the problem size such that you can run the largest problem on that GPU. I suspect that with about `40 GB` of memory available in the GPU, you might be able to use more than `20 Million` grid points in total (you can compute the nx and ny based on the total number of grid points). Please also set `--eager-alloc-percentage` to a fairly small number like `5`. Can you try running the program like that for the two cases you were considering (single and multi-gpu runs)

Here's the command line option: `legate --fbmem <almost-max-mem-in-MB> --eager-alloc-percentage 5 --gpus 1 filename.py --options...`

> When cunumeric uses cpu, it is also much slower than numpy，In the following figure, the default size is 41.

Please try a much larger problem size - how about 10Million points? or 5M? 

I'd also recommend using shared memory, so instead of passing in `--cpus <ncpus>`, pass in `--ompthreads <nthreads>`. Ideally, if the problem size is large enough, you'd be bandwidth bound in this example, so you might want to run [STREAM](https://www.cs.virginia.edu/stream/) benchmark and see when the bandwidth starts to saturate, and use that many threads (or in that ballpark). But to start with, you could just use `4` or `8` threads and see where you are.

> invalid value encountered in multiply

That looks like a NaN was found somewhere in the code! Are you sure the `dt`, `cfl`, `dx` etc. make sense?

> Or, is there any CFD demo that better reflects the performance advantage of cunumeric?

Another option would be to try out the shallow-water equation solver ([here](https://github.com/shriram-jagan/TorchSWE/tree/cunumeric-no-mpi4py)) we modified from Pi-Yueh's original version ([link](https://github.com/piyueh/TorchSWE.git)). The problem size you may need to run at will likely be in several tens of millions of grid points for that as well, and you'd need a new conda environment, install a new package etc., so I'd suggest sticking with the CFD example and perform the tests I suggested earlier, and let us know what you find, so that we can recommend next steps for you.

Let us know what you find!

**Comment by AngryBear2** [comment]
I think it's probably something wrong with my cunumeric, I used the cunumeric on another machine, and in the cpu environment, multithreading started to work. But when I used `--ompthreads 1`, I used `htop` and found that all my cores were running. Currently using cunumeric on the cpu is still a little slower than numpy, and increasing the problem size does seem to close the gap between them, but I don't have enough memory to use a larger problem size. Thank you.

**Comment by shriram-jagan** [comment]
Marking this as closed. If you need further assistance, please reopen this issue.

**Comment by AngryBear2** [comment]
@shriram-jagan Sir, here I go again. For the test of CFDPython mentioned on the cunumeric homepage, can you provide the parameters and data of the experiment settings?

**Comment by shriram-jagan** [comment]
@AngryBear2 let me create a new issue to track your new request separately. Please track the request for the benchmark configuration [here](https://github.com/nv-legate/cunumeric/issues/1087).
