### ISSUE TITLE
cunumeric to torch tensor

### ISSUE THREAD

**Issue by reymondzzzz** [nv-legate/cunumeric#124]
Can I convert cunumeric to torch tensor without copy to host?

**Comment by magnatelee** [comment]
That's not possible at the moment, because cuNumeric and PyTorch are very different in how they manage distributed tensors. We're currently planning to add ingress/egress APIs so that you can take existing tensors in and out of cuNumeric without making copies, though you will still need to figure out how to convert that exported tensor, which will be agnostic to consumer libraries, to a torch tensor.
