### ISSUE TITLE
Handle ufunc coverage wrappers more robustly

### ISSUE THREAD

**Issue by bryevdv** [nv-legate/cunumeric#270]
ref: https://github.com/nv-legate/cunumeric/pull/268/files#r846513290

As noted in the above conversation, the generic callable wrapping for adding coverage reporting is not sufficient. 

Numpy (and thus cunumeric) `ufunc` are objects with their own API (https://numpy.org/doc/stable/reference/ufuncs.html) and just using a plain function wrapper makes those methods invisible. Some requirements to decide first:

* Do all the methods of a `ufunc` need to be included in coverage reporting? Or just its `__call__`

If yes, we will need to resort to a wrapping object (and then: is it sufficient to just create a purpose-built `ufunc_wrapper` or do we need a generic forwarding wrapper?)

If not, we may be able to just wrap and replace `__call__` using the function wrappers similar to the existing ones.

**Comment by magnatelee** [comment]
Though in theory we should report coverage on all those methods in `ufunc`, I doubt that they are actually used that much. Plus, many of those functions have aliases in the top-level module that I believe are more likely being used. So, unless we find someone who really wants to see those methods counted, let's track only two methods `__call__` and `reduce` for now so that our own reporting tool stops breaking the tests.

**Comment by bryevdv** [comment]
@magnatelee do we actually need to track `reduce` or just make sure it is still available and callable?

**Comment by magnatelee** [comment]
@bryevdv I guess we don't want to track it, as many of the ufuncs are missing that function and we don't intend to implement those.
