### ISSUE TITLE
richardson_lucy example crashes with large filter size

### ISSUE THREAD

**Issue by eddy16112** [nv-legate/cunumeric#276]
The example is https://github.com/nv-legate/cunumeric/blob/branch-22.05/examples/richardson_lucy.py
If running with `richardson_lucy.py -t -fx=512 -fy=256 -fz=151 -x=2048 -y=1024 -z=604`, then I am running to the following errors:
```
Internal cuFFT failure with error code 4 in file cunumeric/convolution/convolve.cu at line 1133
Internal cuFFT failure with error code 1 in file cunumeric/cudalibs.cu at line 88
```
Even if I set `x=fx, y=fy, z=fz`, it still crashes.

**Comment by magnatelee** [comment]
this should be fixed by #279. @eddy16112 can you pull my branch and see if that fixes the issue?

**Comment by magnatelee** [comment]
leaving a note to myself and others: the issue was caused by the `convolve` implementation trying to call cuFFT with pointers that are not 8B aligned. This is actually a documented behavior: https://docs.nvidia.com/cuda/cufft/index.html#function-cufftexecr2c-cufftexecd2z Though this fix addresses the reported issue, I'll revert #204, which originally introduced this bug; while fixing the bug, it turns out that cuFFT callbacks make the convolution slower more than 3X for some unfortunate shapes, which is too great to justify the saving on memory space for temporary allocations.

**Comment by magnatelee** [comment]
@eddy16112 Please pull and try again.

**Comment by eddy16112** [comment]
It works for me. Thank you!
