### ISSUE TITLE
uint128 is not supported in PowerPC

### ISSUE THREAD

**Issue by eddy16112** [nv-legate/cunumeric#290]
https://github.com/nv-legate/cunumeric/blob/branch-22.05/src/cunumeric/divmod.h#L20-L24
The code restrict the uint128 to x86 machine. I removed the `#if defined(__x86_64)`, and it works for PowerPC.

**Comment by manopapad** [comment]
@lightsighter I believe you originally wrote this code. Do you know if there's anything x86-specific about it?

**Comment by lightsighter** [comment]
> I believe you originally wrote this code. Do you know if there's anything x86-specific about it?

I borrowed it from CUTLASS :)

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/uint128.h

I don't think there's anything x86 specific about it, but it does seem to be GCC specific, and even then only for specific architectures:

https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/_005f_005fint128.html#g_t_005f_005fint128

**Comment by manopapad** [comment]
It looks like `defined(__SIZEOF_INT128__)` is the suggested way to query for 128-bit int support. https://github.com/nv-legate/cunumeric/pull/293 updates our check to use this instead of checking for x86 specifically. @eddy16112 could you please re-build with this patch and see if it works on your PowerPC platform?

**Comment by eddy16112** [comment]
@manopapad Your PR works fine.

**Comment by manopapad** [comment]
Fixed with #293
