### ISSUE TITLE
Catching out-of-bounds errors when doing advanced indexing

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#31]
In NumPy, basic slices can lie partially or completely outside the bounds of an array, and the out-of-bounds indices are simply ignored. However, requesting out-of-bounds indices is an error when using advanced indexing:

```
>>> np.arange(10)[ 12:14 ]
array([], dtype=int64)
>>> np.arange(10)[ [12,13] ]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 12 is out of bounds for axis 0 with size 10
```

Currently in Legate such cases of advanced indexing are implemented using gather/scatter copies, where out-of-bounds indices are currently ignored, so we are not emitting an error for this case.

We have requested support for a check at the Realm level (see https://github.com/StanfordLegion/legion/issues/1084), but even when this is implemented we may want to avoid it, as copies will be much faster without it.

**Comment by ipdemes** [comment]
I propose following:
1) in case there are several index arrays are sent to the advanced indexing operation, I can check bounds inside of the ZIP task
 2 ) for the case when there is a single index array sent to the advanced indexing operation, there are 2 approaches I can take:
   a) call ZIP task on a single array and get indices checked inside
   b) have a separate task that will get a single Logical region and shape of and base array and check the indices.
   c) use boolean operations on ndarrays like `np.all(arr>0)`
   
2a will end up creating output region we don't use, so 2b might be a better approach
2c will create an intermediate boolean array

Alternatively we can just rely on Realm to check the bounds, but it seems like copies might be slower with the check.

 @manopapad  @lightsighter and Artem, what do you think on this?

**Comment by manopapad** [comment]
My understanding is that there's ongoing work on improving Realm's implementation of scatter-gather copies, and some corresponding pre-partitioning code is being added on the Legion side. If that's indeed the case, I was wondering if that means such bounds checks will now be done by Legion automatically, so we wouldn't have to add anything on the cuNumeric side.

**Comment by lightsighter** [comment]
The plan is for Legion to do the image/preimage to reduce the number of instances that Realm will need to scatter/gather to/from for scalability reasons. @ipdemes intuition that having Realm do the checks is expensive is accurate. Legion technically wouldn't be in a place to detect the out-of-bounds cases because the image/preimage operations will just silently drop out-of-bounds cases, unless we add a mechanism to detect out-of-bounds cases in image/preimage. I suppose we can do that and then Legion could run a meta-task to see if you get any out-of-bounds cases. That work might still be a little ways off. I think improving the scalability of advanced indexing is probably the priority over detecting the out-of-bounds errors for now. 

I kind of like option 2(b) for now. You can imagine doing something like launching the check task and getting back a boolean future saying whether everything is in bounds or not. To avoid blocking deferred execution, you don't need to block on it right away; you can optimistically assume everything is in bounds and grab a copy of the stacktrace in case you need to issue an exception later. Each time the Legate store is used, you can check the future and see if it is ready. If it is you can check it and raise a python exception (with the stacktrace you captured earlier for the right callsite) if things are out of bounds. Ultimately you might need to block before the Legate Store is garbage collected and you won't be able to check the future anymore, but at least you made it as far as possible without blocking. @magnatelee for visibility since doing that would probably require some help from the Legate Core. It's like a Maybe monad wrapping a Legate Store.

**Comment by apryakhin** [comment]
+1 on @lightsighter but in general I think it depends on what numbers we are talking about here. For unstructured gathers/scatters, we need to iterate over the points in the index space in any case which means out-of-bounds checks will be done in O(N). It does look that algorithmically we should not get worse. However, we will introduce a time delta per point which will certainly makes us slower in 'practical numbers'. How large this delta will be and whether it's acceptable - probably a subject to a debate. 

I am not getting what's the different 2a and 2b?..e.g. what's is the ZIP task vs 'separate task'? but checking out-of-bounds on the index arrays in a separate task in the upper layer sounds fine to me.

**Comment by ipdemes** [comment]
@apryakhin ZIP task gets several index arrays and returns single array with Point<N> field on it. I already have it implemented and thought I might just reuse it. 

@lightsighter Makes sense. I will do a separate task with the future as you described. I will work with @magnatelee in case I need some help from Legate Core.

**Comment by magnatelee** [comment]
I like 2b as well, and I actually want to take this as an opportunity to add support for exceptions to Legate Core, though the scheme I have in mind is not necessarily associating Legate stores with exceptions. @ipdemes this definitely needs changes in the legate core and I'll probably give you an interface through which you can raise an exception in a C++ task, which will be re-thrown on the Python land. I'm still debating whether the bounds checks should also be part of Legate Core, as indirect copies are Legate operations and not cuNumeric tasks, but you can start working on the task for bounds checks. We can later decide where we should put it.

**Comment by ipdemes** [comment]
@manopapad sure, I will let you know when I have the task implemented in cuNumeric

**Comment by ipdemes** [comment]
This issue has been fixed and example from above would return: `IndexError: index is out of bounds in index array`
