### ISSUE TITLE
np.random.shuffle issues warning indicating numpy fall back but then hangs

### ISSUE THREAD

**Issue by mmccarty** [nv-legate/cunumeric#798]
When testing the differences between NumPy, CuPy, and cuNumeric is ran into an issue with `np.random.shuffle`. Below is 
 the reproducer...

```
import sys

if sys.argv[1] == 'cupy':
    import cupy as np
    print("Use cupy")
elif sys.argv[1] == 'cunumeric':
    import cunumeric as np
    print("Use cunumeric")
elif sys.argv[1] == 'numpy':
    import numpy as np
    print("Use numpy")
else:
    raise Exception("Unknown arg: " + sys.argv[1])

import random
import time

# Size of dataset to be generated. The final size is 4 * data_size
data_size = 1_000_00
num_iters = 5
num_clusters = 4

# sample from Gaussians
data1 = np.random.normal(5, 4, size=(data_size,3))
data2 = np.random.normal(20, 3, size=(data_size, 3))
data3 = np.random.normal(25, 5, size=(data_size,3))
data4 = np.random.normal(30, 5, size=(data_size,3))

# Combine the data to create the final dataset
data = np.concatenate((data1,data2, data3, data4), axis = 0)
print("Data size: ", data.size)

# Shuffle the data
np.random.shuffle(data)
```

This completes as expected with NumPy and CuPy.
```
legate --gpus 2 shuffle.py numpy
Use numpy
Data size:  1200000
```

However, cuNumeric prints the following warnings and hangs...

```
$ legate --gpus 2 shuffle.py cunumeric
Use cunumeric
Data size:  1200000
shuffle.py:35: RuntimeWarning: cuNumeric has not implemented numpy.random.shuffle and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.random.shuffle(data)
/home/mmccarty/mambaforge/envs/cunumeric/lib/python3.1/site-packages/cunumeric/coverage.py:195: UserWarning: you are shuffling a 'ndarray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  return func(*args, **kwargs)
```

I understand from the warning that shuffle is not implemented, but I wonder why the fall back to numpy is hanging?

**Comment by manopapad** [comment]
The root cause here is that we have been depending on NumPy functions to automatically convert non-`np.ndarray` arguments to `np.ndarray`s at entry. Thus far this has been the case, but `np.random.shuffle` in particular is not doing that (presumably because it also wants to work on any random-access sequence). Instead it seems to be implementing the shuffle in a generic way, through repeated pairwise swaps (or some similar method), which works fine on a single CPU, but is a terrible way to implement shuffling on top of a GPU-memory/distributed array.

So what ends up happening in your example is that, instead of converting the cuNumeric array to a NumPy array and doing the operation on that, NumPy is emitting thousands of single-element-modifying operations, which will take forever to complete.

The long-term solution is to implement `np.random.shuffle` in cuNumeric, but for now I made some changes in #802 to preemptively convert cuNumeric arrays to NumPy on our side, instead of relying on NumPy to do this.

**Comment by manopapad** [comment]
@mmccarty #802 has been merged, can you confirm that it's not hanging for you anymore?

**Comment by mmccarty** [comment]
Thanks, @manopapad 
I will take a look this week. I assume this isn't release on the conda channel and I would need to build from source. Correct?

**Comment by manopapad** [comment]
That's correct, unfortunately.

**Comment by bryevdv** [comment]
@manopapad @mmccarty Just FYI both version run fine for me on latest `branch-23.05`
```
docs310 ❯ legate --gpus 2 ~/tmp/shuffle.py cunumeric
Use cunumeric
Data size:  1200000
/home/bryan/tmp/shuffle.py:34: RuntimeWarning: cuNumeric has not implemented numpy.random.shuffle and is falling back to canonical NumPy. You may notice significantly decreased performance for this function call.
  np.random.shuffle(data)

~/work/cunumeric branch-23.05
docs310 ❯ legate --gpus 2 ~/tmp/shuffle.py numpy    
Use numpy
Data size:  1200000

~/work/cunumeric branch-23.05
```

**Comment by mmccarty** [comment]
Thanks @bryevdv ! I've confirmed the fix as well. Closing issue. And thanks @manopapad !
